MainCPP: file/main.cpp
IOFile: TEST
Count: 10
Range: [

]
Config: |
  n number 1 1000
  ------
  n
TestFolder: file/testcases/
OJFormatFolder: file/test_oj/
ZipFile: file/testcase.zip
OJZipFile: file/test_oj.zip
DebugFile: true
LogMemory: true
TimeMeasure: true

# Xem thêm ở file README.md