TestCount: 5
TestRange: [
    { range: [0, 1], count: 10 }
]
TestCode: |
    n number 1 100
    ------
    const n
    [n, 1 - n]

MainCodePath: 
TestcasesPath: file/testcases
TestcasesZip:
OJ_TestcasesPath:
OJ_TestcasesZip:

IOFilename: TEST
Compiler: g++
CppVersion: c++17
Zip_Program: package