Count: 10
Range: [

]
Config: >
  n number 1 1000
  ------
  n
TestFolder: file/testcases/
OJFormatFolder:
MainCPP: file/main.cpp
ZipFile: file/testcase.zip
OJZipFile: 
DebugFile: true
LogMemory: true
TimeMeasure: true
CustomFunc: 

# Xem thêm ở file README.md